name: Auto-Update PS5 Payloads JSON

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Otorga permisos explícitos para hacer git push

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Asegura descargar todo el historial de git

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ejecutar script de actualización
        run: python update_payloads.py

      - name: Guardar y subir cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add payloads.json
          
          # Verifica si hay cambios antes de hacer commit/push para evitar el exit code 128
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update: Últimas versiones de payloads"
            git push
          else
            echo "No se detectaron cambios en payloads.json."
          fi
