name: Auto-Update PS5 Payloads JSON

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'

      - name: Ejecutar script de actualización
        run: python update_payloads.py

      - name: Guardar y subir cambios
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add -u
          
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update: Últimas versiones de payloads"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No se detectaron cambios en el repositorio."
          fi
